server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://47.108.167.244:3306/shopping?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: zxcv1234
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: 47.108.167.244:8848